version: '3.8'

services:
  service-status:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Optional: Add SSL termination with Let's Encrypt
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - certs:/etc/nginx/certs
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #   environment:
  #     - DEFAULT_HOST=service-status.garyzone.pro

# volumes:
#   certs:
#   vhost:
#   html:
